sudo: false
language: python
services:
  - postgresql

addons:
  postgresql: "9.6"

cache:
  directories:
    - $HOME/.cache/pip
    
env:
  global:
    - TEST=-v

matrix:
  include:
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install -U pip
  - pip install -r requirements.txt
  - pip install pytest
  - pip install -e .

before_script:
  - .ci/install-sqlflow-pg.sh

script:
    - pytest -vv
